import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// Available languages
export type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
export const translations = {
  zh: {
    // Navbar
    'home': '首页',
    'product_search': '产品搜索',
    'workspace': '工作台',
    'low_carbon_recommendations': '低碳推荐',
    'login': '登录',
    
    // Hero section
    'hero_badge': '可持续未来的智能选择',
    'hero_title_1': '智能分析产品碳足迹',
    'hero_title_2': '引领绿色供应链革新',
    'hero_description': '通过AI驱动的精准碳足迹分析，帮助企业优化供应链，实现可持续发展目标，提升市场竞争力。',
    'search_placeholder': '搜索产品或供应商...',
    'search_button': '搜索',
    'tags': ['电子产品', '纺织品', '食品饮料', '建筑材料', '包装材料'],
    'start_prediction': '开始预测产品碳足迹',
    'view_recommendations': '查看低碳供应商推荐',
    
    // Features section
    'core_features': '核心功能',
    'features_description': '通过先进的AI技术和专业的碳足迹分析方法，我们为企业提供全方位的低碳转型解决方案',
    'feature_search_title': '产品碳足迹搜索与浏览',
    'feature_search_desc': '快速搜索产品和供应商的碳足迹数据，清晰了解数据来源，获取相关低碳建议。',
    'feature_prediction_title': '产品碳足迹预测',
    'feature_prediction_desc': '基于AI推理技术，对产品碳足迹进行精准预测，生成详细分析报告和可视化结果。',
    'feature_comparison_title': '竞品碳足迹对比',
    'feature_comparison_desc': '多维度比较竞争对手产品的碳足迹表现，识别市场优势和优化空间。',
    'feature_data_request_title': '供应商数据请求',
    'feature_data_request_desc': '一键生成专业的数据请求，通过多种渠道与供应商高效沟通，获取真实碳足迹数据。',
    'feature_recommendation_title': '低碳供应商推荐',
    'feature_recommendation_desc': '智能推荐碳足迹表现优异的供应商，展示减碳亮点和最佳实践案例。',
    
    // Call to Action section
    'cta_title': '开始您的低碳供应链之旅',
    'cta_description': '立即使用我们的AI驱动碳足迹分析工具，挖掘减碳潜力，发现商业机遇，引领可持续发展。',
    'search_products': '搜索产品碳足迹',
    
    // Recent Products section
    'recent_products_title': '最新产品碳足迹',
    'recent_products_desc': '浏览最新添加的产品碳足迹数据，掌握行业绿色发展动态',
    'view_all': '查看全部',
    'actual_data': '实际数据',
    'prediction_result': '预测结果',
    'details': '详情',
    
    // Low Carbon Recommendations section
    'low_carbon_suppliers_title': '优秀低碳供应商推荐',
    'low_carbon_suppliers_desc': '发现碳足迹表现卓越的供应商，助力绿色供应链建设',
    'view_all_recommendations': '查看全部推荐',
    'carbon_footprint_rating': '碳足迹评分',
    'low_carbon_highlights': '低碳亮点',
    'view_supplier_details': '查看供应商详情',
    
    // Footer
    'company_description': '专注于提供产品碳足迹分析和环保供应链优化的先进解决方案。让可持续发展成为每个企业的竞争优势。',
    'company_address': '上海市浦东新区张江高科技园区',
    'quick_links': '快速链接',
    'lca_inference': 'LCA模型推理',
    'data_request_link': '数据请求',
    'resource_center': '资源中心',
    'carbon_footprint_wiki': '碳足迹百科',
    'industry_reports': '行业报告',
    'best_practices': '最佳实践',
    'policy_updates': '政策动态',
    'faq': '常见问题',
    'subscribe': '订阅动态',
    'subscribe_desc': '订阅我们的新闻邮件，及时了解最新的可持续发展趋势和产品更新。',
    'email_placeholder': '您的邮箱地址',
    'subscribe_button': '订阅',
    'privacy_policy': '隐私政策',
    'terms_of_use': '使用条款',
    'about_us': '关于我们',
    
    // Comparison Chart
    'uncertainty_range_info': '误差棒表示碳足迹计算的不确定度范围',
    'industry_benchmark': '行业基准',
    'lowest_competitor': '最低竞品',
    'carbon_footprint_value': '碳足迹值',
    
    // Prediction Result
    'prediction_result_badge': '预测结果',
    'prediction_date': '预测日期',
    'copy_link': '复制链接',
    'share': '分享',
    'export_report': '导出报告',
    'request_supplier_data': '请求供应商实际数据',
    'request_data_tooltip': '预测数据只是基于现有信息的估算。请求供应商提供实际数据，以获得更精确的碳足迹分析。',
    'product_info': '产品详细信息',
    'reference_sources': '参考来源',
    
    // Prediction Result additional translations
    'view_report': '查看报告',
    'carbon_footprint_breakdown': '碳足迹组成明细',
    'uncertainty_range': '不确定度范围',
    'prediction_history': '历史预测记录',
    
    // PredictionResult component translations
    'carbon_footprint_prediction_result': '碳足迹预测结果',
    'product_carbon_industry_comparison': '产品碳足迹值与行业对比分析',
    'industry_comparison_analysis': '行业对比分析',
    'main_component_analysis': '主要组成分析',
    'carbon_footprint_composition': '碳足迹主要来源组成',
    'lifecycle_phase_analysis': '生命周期阶段分析',
    'carbon_footprint_distribution': '产品全生命周期各阶段碳足迹分布',
    'emission_reduction_suggestions': '减排优化建议',
    'carbon_reduction_suggestions_desc': '基于产品特性和行业最佳实践的碳减排建议',
    'similar_products_comparison': '相似产品对比',
    'similar_products_comparison_desc': '与市场上同类产品的碳足迹对比',
    'compared_to_current': '低于当前产品',
    'higher_than_current': '高于当前产品',
    'click_for_details': '点击查看详情',
    
    // Workspace Request Management
    'request_management': '请求管理',
    'request_records': '请求记录',
    'search_requests': '搜索请求...',
    'filter_status': '状态筛选',
    'all_statuses': '全部状态',
    'request_details': '请求详情',
    'request_id': '请求 ID',
    'supplier': '供应商',
    'product': '产品',
    'contact_method': '联系方式',
    'send_date': '发送日期',
    'response_deadline': '响应截止日期',
    'response_progress': '响应进度',
    'request_content': '请求内容',
    'request_attachments': '请求附件',
    'download': '下载',
    'supplier_response': '供应商响应',
    'send_reminder': '发送提醒',
    'export_details': '导出详情',
    'cancel_request': '取消请求',
    'select_request_view_details': '选择请求查看详情',
    'select_request_description': '从左侧列表中选择一个请求记录，查看详细信息和供应商响应',
    
    // Workspace Data Collections
    'data_collections': '数据集合',
    'product_carbon_data': '产品碳足迹数据',
    'production_process_data': '生产工艺数据',
    'last_updated': '最后更新',
    'view': '查看',
    'product_carbon_data_desc': '包含50个不同产品的碳足迹数据',
    'production_process_data_desc': '包含30种不同生产工艺的能耗数据',
    
    // Search Page
    'product_carbon_footprint_search': '产品碳足迹搜索',
    'search_product_supplier_category': '搜索产品名称、供应商或类别...',
    'filter': '筛选',
    'filter_and_sort': '筛选与排序',
    'industry': '行业',
    'data_type': '数据类型',
    'sort_by': '排序方式',
    'clear_filters': '清除筛选',
    'applied_filters': '已应用筛选',
    'search': '搜索',
    'sort': '排序',
    'clear_all': '清除全部',
    'found': '找到',
    'results': '个结果',
    'no_results_found': '未找到相关结果',
    'try_adjusting_search': '尝试调整搜索条件或筛选选项，也可以使用我们的预测功能生成新的碳足迹数据。',
    'start_new_prediction': '开始新的预测',
    'related_supplier_recommendations': '相关供应商推荐',
    'product_count': '产品数量',
    
    // Workspace General
    'return_to_home': '返回主页',
    'return': '返回',
    'menu': '菜单',
    'workspace_modules': '工作台模块',
    'function_modules': '功能模块',
    'pro_features': '专业版功能',
    'pro_features_desc': '使用专业版解锁更多高级功能与数据分析',
    'upgrade_to_pro': '升级专业版',
    'close': '关闭',
    'data_request': '数据请求',
    
    // Workspace Inference
    'carbon_footprint_prediction': '碳足迹预测',
    'new_prediction': '新建预测',
    'history_records': '历史记录',
    'in_progress': '进行中',
    'no_active_predictions': '当前没有进行中的预测任务',
    'prediction_history_title': '预测历史记录',
    'history_prediction_list': '历史预测列表',
    'view_details': '查看详情',
    
    // Workspace Data Request
    'new_request': '新建请求',
    'historical_requests': '历史请求',
    'redirect_from_prediction': '从预测结果页面跳转',
    'creating_data_request': '您正在为',
    'of_supplier': '的产品',
    'creating_data_request_2': '创建数据请求。',
    'prefilled_info': '我们已为您预填了部分信息，请补充完整其余内容。',

    // InferenceForm
    'product_name_placeholder': '产品名称（如：有机棉T恤）',
    'product_category_placeholder': '产品类别（如：纺织品、电子产品）',
    'supplier_info': '供应商信息',
    'supplier_name_placeholder': '供应商名称（如：绿能科技有限公司）',
    'product_description': '产品描述（可选）',
    'product_description_placeholder': '简要描述产品特性、材料、制造工艺等信息，将有助于提高预测准确性',
    'environmental_tips': '环保小贴士',
    'environmental_tips_desc': '提供详细的产品信息可以帮助我们更准确地预测碳足迹。如有产品技术文档，可在预测后上传以提高准确性。',
    'cancel_prediction': '取消预测',
    'save_draft': '保存草稿',
    
    // PredictionResult
    'return_button': '返回',
    'link_copied': '链接已复制',
    'link_copied_desc': '预测结果链接已复制到剪贴板',
    'prediction_needs_accuracy': '预测数据存在不确定性？',
    'prediction_accuracy_desc': '本页面显示的数据仅为预测结果，可能与实际情况存在差异。向供应商请求实际数据，获取更精准的碳足迹分析与减排建议。',
    'need_more_accurate_data': '需要更准确的数据分析？',
    'accurate_data_desc': '通过获取供应商的实际生产数据，我们可以为您提供更精确的碳足迹分析和减排方案。向供应商发送数据请求，只需几分钟即可完成。',
    'prediction_disclaimer': '本结果由企业已披露信息及相关统计数据推理得到，仅为预测结果，不能完全反映供应商实际生产水平。对于碳核算、认证场景，应使用企业实际数据，实际数据缺失时，将采用已有行业均值数据作为缺省值。',
    'improvement_difficulty_easy': '容易',
    'improvement_difficulty_medium': '中等',
    'improvement_difficulty_hard': '困难',
    'potential_reduction': '潜在减排',

    // Data Request Form
    'supplier_product_info_form': '供应商与产品信息',
    'supplier_name_form': '供应商名称',
    'supplier_name_placeholder_form': '请输入供应商名称',
    'product_name_form': '产品名称',
    'product_name_placeholder_form': '请输入产品名称',
    'contact_info_form': '联系信息',
    'contact_name_form': '联系人姓名',
    'contact_name_placeholder_form': '请输入联系人姓名',
    'contact_email_form': '联系邮箱',
    'contact_email_placeholder_form': '请输入联系邮箱',
    'contact_phone_form': '联系电话（选填）',
    'contact_phone_placeholder_form': '请输入联系电话',
    'request_data_items': '请求数据项',
    'request_data_items_description': '选择您需要供应商提供的数据类型',
    'product_specs': '产品规格参数',
    'material_composition': '材料组成情况',
    'manufacturing_process': '制造工艺流程',
    'energy_consumption': '能源消耗数据',
    'transportation_logistics': '运输物流信息',
    'certifications': '相关认证文件',
    'test_reports': '检测报告数据',
    'packaging_details': '包装材料详情',
    'suppliers_info': '上游供应商信息',
    'waste_data': '废弃物处理数据',
    'urgency_level': '紧急程度',
    'urgency_low': '低 - 一个月内回复',
    'urgency_medium': '中 - 两周内回复',
    'urgency_high': '高 - 一周内回复',
    'response_deadline_form': '响应截止日期',
    'select_date': '选择日期',
    'additional_info_form': '附加说明（选填）',
    'additional_info_placeholder': '请输入任何需要补充的信息或特殊要求',
    'preview_request_ignore_validation': '预览请求（忽略验证）',
    'validate_and_preview': '验证并预览',
    
    // Data Request Preview
    'data_request_preview': '数据请求预览',
    'confirm_content_accuracy': '请确认以下内容是否准确，准确无误后点击发送',
    'supplier_info_label': '供应商信息',
    'supplier_name_label': '供应商名称',
    'product_info_label': '产品信息',
    'product_name_label': '产品名称',
    'contact_info_label': '联系信息',
    'contact_name_label': '联系人',
    'contact_email_label': '邮箱',
    'contact_phone_label': '电话',
    'request_details_label': '请求详情',
    'requested_data': '请求的数据',
    'urgency_level_label': '紧急程度',
    'response_deadline_label': '响应截止日期',
    'additional_notes': '附加说明',
    'email_info': '邮件信息',
    'email_subject': '邮件主题',
    'email_content': '邮件内容',
    'carbon_footprint_chart': '此邮件将包含以下碳足迹对比图：',
    'chart_note': '注：此图表将作为图片附件或嵌入内容发送',
    'return_to_edit': '返回编辑',
    'confirm_send': '确认发送',
    
    // Email Content
    'email_subject_template': '关于{product}碳足迹数据收集 - {supplier}',
    'email_greeting': '尊敬的{supplier}团队：',
    'email_hello': '您好！',
    'email_intro_with_name': '我们是{name}，来自碳知源环保科技有限公司的采购团队。我们最近一直在关注贵公司的{product}，对其性能和环保特性非常感兴趣。',
    'email_intro_without_name': '我们是碳知源环保科技有限公司的采购团队。我们最近一直在关注贵公司的{product}，对其性能和环保特性非常感兴趣。',
    'email_purpose': '作为一家重视可持续发展的企业，我们正在对所有供应链产品进行碳足迹评估，以期打造更加环保的产品线。在浏览贵公司产品资料的过程中，我们注意到{product}在行业内具有竞争力，因此希望能获取更详细的产品碳足迹数据，以便我们做出更全面的评估。',
    'current_prediction_title': '【当前产品预测结果】',
    'current_prediction_intro': '根据我们平台对{product}的初步碳足迹预测：',
    'current_prediction_value': '• 预计碳足迹值：{value} {unit}',
    'current_prediction_confidence': '• 置信水平：{level}',
    'current_prediction_uncertainty': '• 不确定性范围：{range}',
    'current_prediction_contributors': '• 主要贡献因素：{contributors}',
    'current_prediction_disclaimer': '以上预测结果可能与实际情况存在差异，我们希望通过获取更准确的数据来优化此预测结果。',
    'requested_items_intro': '具体来说，我们希望获取以下信息：',
    'market_comparison_title': '【市场对比数据】',
    'industry_benchmark_title': '【行业基准数据】',
    'platform_prediction_title': '【关于平台预测数据说明】',
    'platform_prediction_desc': '请注意，我们平台提供的碳足迹预测数据具有以下特点：',
    'platform_prediction_point1': '• 预测结果主要基于公开披露的行业数据及AI推理技术',
    'platform_prediction_point2': '• 预测数据存在一定程度的不确定性（通常在±15%范围内）',
    'platform_prediction_point3': '• 预测结果可能无法完全反映实际生产情况或特定工艺差异',
    'platform_prediction_point4': '• 获取您的实际数据将帮助我们提高预测准确性，并为您提供更有针对性的减碳建议',
    'reports_intro': '以下是我们整理的相关行业报告，您可能会感兴趣：',
    'data_submission_title': '【数据填报链接】',
    'data_submission_desc': '为了方便您提交相关数据，我们创建了一个专属数据填报页面，您可以通过以下链接进行填报：',
    'data_submission_security': '该链接是为贵公司专门生成的安全链接，无需注册即可直接填报数据。链接有效期为30天。',
    'closing_with_deadline': '如果贵公司能够提供这些数据，将极大地帮助我们评估{product}在我们供应链中的环保表现，并为后续可能的合作奠定基础。由于项目进度安排，希望能在{deadline}前收到相关信息。此请求为{urgency}。',
    'closing_without_deadline': '如果贵公司能够提供这些数据，将极大地帮助我们评估{product}在我们供应链中的环保表现，并为后续可能的合作奠定基础。希望能尽快收到您的回复。此请求为{urgency}。',
    'additional_info_section': '补充说明：\n{info}',
    'email_thanks': '感谢您的关注与支持！期待与贵公司进一步合作。',
    'email_closing': '祝商祺！',
    'email_signature': '{name}\n{email}\n{phone}\n碳知源环保科技有限公司',
    'urgency_text_low': '低优先级',
    'urgency_text_medium': '常规优先级',
    'urgency_text_high': '高优先级',
    'unspecified_supplier': '未指定供应商',
    'unspecified_product': '未指定产品',
    'unspecified_contact': '未指定联系人',
    'unspecified_email': '未指定邮箱',
    'no_items_selected': '未选择数据项',
    'asap': '尽快',
    
    // Prediction Confidence Levels
    'confidence_level_low': '低',
    'confidence_level_medium': '中等',
    'confidence_level_high': '高',
    
    // Prediction Contributors
    'contributor_materials': '原材料生产',
    'contributor_manufacturing': '制造工艺',
    'contributor_transportation': '运输',
    
    // Inference Stages
    'stage_collecting_info': '正在收集产品基础信息...',
    'stage_analyzing_composition': '分析产品组成信息...',
    'stage_getting_tech_info': '获取生产技术信息...',
    'stage_identifying_competitors': '识别相关竞品供应商...',
    'stage_building_lca': '构建LCA模型...',
    'stage_calculating_footprint': '计算碳足迹值...',
    'stage_generating_report': '生成预测报告...',
    'stage_prediction_complete': '预测完成！',
    'estimated_completion_time': '预计完成时间: 40-60秒',
    
    // Form Validation
    'required_fields_error': '请提供产品名称和供应商名称',
    'product_name_required': '请输入产品名称',
    'supplier_name_required': '请输入供应商名称',
    'validation_error': '表单验证错误',
    
    // LCA Model Card
    'lca_model_flowchart': 'LCA模型流程图',

    // Recommendation Page
    'low_carbon_recommendation': '低碳推荐',
    'recommendation_description': '发现优秀的低碳供应商、产品和最佳实践，加速您的可持续发展之旅',
    'search_recommendations': '搜索推荐...',
    'low_carbon_suppliers': '低碳供应商',
    'low_carbon_products': '低碳产品',
    'carbon_reduction_best_practices': '减碳最佳实践',
    'all_industries': '全部行业',
    'renewable_energy': '可再生能源',
    'material_science': '材料科学',
    'energy_storage': '储能技术',
    'electronics_manufacturing': '电子制造',
    'building_materials': '建筑材料',
    'all_categories': '全部类别',
    'solar_energy': '太阳能',
    'wind_energy': '风能',
    'battery_technology': '电池技术',
    'composite_materials': '复合材料',
    'smart_hardware': '智能硬件',
    'green_building_materials': '绿色建材',
    'all_regions': '全部地区',
    'east_china': '华东',
    'south_china': '华南',
    'north_china': '华北',
    'central_china': '华中',
    'west_china': '西部',
    'sort_by': '排序方式',
    'carbon_performance_score': '碳绩效得分',
    'overall_rating': '综合评分',
    'latest_added': '最新添加',
    'all_data': '全部数据',
    'measured_data': '实测数据',
    'predicted_data': '预测数据',
    'carbon_reduction_level': '降碳水平',
    'significant_reduction': '显著降碳 (>40%)',
    'medium_reduction': '中等降碳 (20-40%)',
    'slight_reduction': '轻微降碳 (<20%)',
    'reduction_magnitude': '降碳幅度',
    'carbon_footprint_value': '碳足迹值',
    'industry_applicability': '行业适用性',
    'manufacturing': '制造业',
    'energy_industry': '能源行业',
    'chemical_industry': '化工行业',
    'electronics_industry': '电子行业',
    'automotive_industry': '汽车行业',
    'implementation_difficulty': '实施难度',
    'easy_to_implement': '容易实施',
    'medium_difficulty': '中等难度',
    'high_difficulty': '高难度',
    'return_on_investment_period': '投资回报期',
    'all_periods': '全部',
    'short_term': '短期 (<1年)',
    'medium_term': '中期 (1-3年)',
    'long_term': '长期 (>3年)',
    'carbon_reduction_effect': '减碳效果',
    'return_on_investment': '投资回报',
    'load_more': '加载更多',
    'carbon_performance': '碳绩效',
    'low_carbon_highlights': '低碳亮点',
    'product_coverage': '产品覆盖',
    'view_details': '查看详情',
    'industry_average': '行业平均',
    'carbon_reduction_highlights': '减碳亮点',
    'implementation_results': '实施成果',

    // Stats
    'carbon_footprint_data_count': '已分析产品数量',
    'industry_coverage_count': '覆盖行业数量',
    'average_carbon_reduction_potential': '平均减碳潜力',
    'user_satisfaction_rate': '用户满意度',
  },
  en: {
    // Navbar
    'home': 'Home',
    'product_search': 'Product Search',
    'workspace': 'Workspace',
    'low_carbon_recommendations': 'Low Carbon',
    'login': 'Login',
    
    // Hero section
    'hero_badge': 'Smart Choice for a Sustainable Future',
    'hero_title_1': 'Intelligent Product Carbon Footprint Analysis',
    'hero_title_2': 'Leading Green Supply Chain Innovation',
    'hero_description': 'Through AI-driven precise carbon footprint analysis, we help companies optimize supply chains, achieve sustainable development goals, and enhance market competitiveness.',
    'search_placeholder': 'Search products or suppliers...',
    'search_button': 'Search',
    'tags': ['Electronics', 'Textiles', 'Food & Beverage', 'Building Materials', 'Packaging'],
    'start_prediction': 'Start Product Carbon Prediction',
    'view_recommendations': 'View Low-Carbon Suppliers',
    
    // Features section
    'core_features': 'Core Features',
    'features_description': 'Using advanced AI technology and professional carbon footprint analysis methods, we provide comprehensive low-carbon transformation solutions for enterprises',
    'feature_search_title': 'Carbon Footprint Search & Browse',
    'feature_search_desc': 'Quickly search product and supplier carbon footprint data, clearly understand data sources, and get relevant low-carbon recommendations.',
    'feature_prediction_title': 'Carbon Footprint Prediction',
    'feature_prediction_desc': 'Based on AI inference technology, precisely predict product carbon footprints, generating detailed analysis reports and visualization results.',
    'feature_comparison_title': 'Competitor Carbon Comparison',
    'feature_comparison_desc': 'Compare competitors\' carbon footprint performance in multiple dimensions, identifying market advantages and optimization opportunities.',
    'feature_data_request_title': 'Supplier Data Requests',
    'feature_data_request_desc': 'Generate professional data requests with one click, communicate efficiently with suppliers through multiple channels, and obtain real carbon footprint data.',
    'feature_recommendation_title': 'Low Carbon Supplier Recommendations',
    'feature_recommendation_desc': 'Intelligently recommend suppliers with excellent carbon footprint performance, showcasing carbon reduction highlights and best practice cases.',
    
    // Call to Action section
    'cta_title': 'Start Your Low-Carbon Supply Chain Journey',
    'cta_description': 'Use our AI-driven carbon footprint analysis tools now to uncover carbon reduction potential, discover business opportunities, and lead sustainable development.',
    'search_products': 'Search Product Carbon Footprints',
    
    // Recent Products section
    'recent_products_title': 'Latest Carbon Footprints',
    'recent_products_desc': 'Browse the latest added product carbon footprint data to keep up with green development trends in the industry',
    'view_all': 'View All',
    'actual_data': 'Actual Data',
    'prediction_result': 'Prediction Result',
    'details': 'Details',
    
    // Low Carbon Recommendations section
    'low_carbon_suppliers_title': 'Excellent Low-Carbon Suppliers',
    'low_carbon_suppliers_desc': 'Discover suppliers with outstanding carbon footprint performance to support green supply chain construction',
    'view_all_recommendations': 'View All Recommendations',
    'carbon_footprint_rating': 'Carbon Footprint Rating',
    'low_carbon_highlights': 'Low Carbon Highlights',
    'view_supplier_details': 'View Supplier Details',
    
    // Footer
    'company_description': 'Focused on providing advanced solutions for product carbon footprint analysis and environmentally friendly supply chain optimization. Making sustainable development a competitive advantage for every business.',
    'company_address': 'Zhangjiang Hi-Tech Park, Pudong New Area, Shanghai',
    'quick_links': 'Quick Links',
    'lca_inference': 'LCA Model Inference',
    'data_request_link': 'Data Request',
    'resource_center': 'Resource Center',
    'carbon_footprint_wiki': 'Carbon Footprint Wiki',
    'industry_reports': 'Industry Reports',
    'best_practices': 'Best Practices',
    'policy_updates': 'Policy Updates',
    'faq': 'FAQ',
    'subscribe': 'Subscribe',
    'subscribe_desc': 'Subscribe to our newsletter to stay updated on the latest sustainable development trends and product updates.',
    'email_placeholder': 'Your email address',
    'subscribe_button': 'Subscribe',
    'privacy_policy': 'Privacy Policy',
    'terms_of_use': 'Terms of Use',
    'about_us': 'About Us',
    
    // Comparison Chart
    'uncertainty_range_info': 'Error bars represent the uncertainty range of carbon footprint calculation',
    'industry_benchmark': 'Industry Benchmark',
    'lowest_competitor': 'Lowest Competitor',
    'carbon_footprint_value': 'Carbon Footprint Value',
    
    // Prediction Result
    'prediction_result_badge': 'Prediction Result',
    'prediction_date': 'Prediction Date',
    'copy_link': 'Copy Link',
    'share': 'Share',
    'export_report': 'Export Report',
    'request_supplier_data': 'Request Supplier Data',
    'request_data_tooltip': 'The prediction data is only an estimate based on existing information. Request actual data from suppliers for more accurate carbon footprint analysis.',
    'product_info': 'Product Information',
    'reference_sources': 'Reference Sources',
    
    // Prediction Result additional translations
    'view_report': 'View Report',
    'carbon_footprint_breakdown': 'Carbon Footprint Breakdown',
    'uncertainty_range': 'Uncertainty Range',
    'prediction_history': 'Prediction History',
    
    // PredictionResult component translations
    'carbon_footprint_prediction_result': 'Carbon Footprint Prediction Result',
    'product_carbon_industry_comparison': 'Product Carbon Footprint and Industry Comparison',
    'industry_comparison_analysis': 'Industry Comparison Analysis',
    'main_component_analysis': 'Main Component Analysis',
    'carbon_footprint_composition': 'Carbon Footprint Composition',
    'lifecycle_phase_analysis': 'Lifecycle Phase Analysis',
    'carbon_footprint_distribution': 'Carbon Footprint Distribution Across Product Lifecycle Phases',
    'emission_reduction_suggestions': 'Emission Reduction Suggestions',
    'carbon_reduction_suggestions_desc': 'Carbon reduction suggestions based on product characteristics and industry best practices',
    'similar_products_comparison': 'Similar Products Comparison',
    'similar_products_comparison_desc': 'Carbon footprint comparison with similar products in the market',
    'compared_to_current': 'Lower than current product',
    'higher_than_current': 'Higher than current product',
    'click_for_details': 'Click for details',
    
    // Workspace Request Management
    'request_management': 'Request Management',
    'request_records': 'Request Records',
    'search_requests': 'Search requests...',
    'filter_status': 'Filter by Status',
    'all_statuses': 'All Statuses',
    'request_details': 'Request Details',
    'request_id': 'Request ID',
    'supplier': 'Supplier',
    'product': 'Product',
    'contact_method': 'Contact Method',
    'send_date': 'Send Date',
    'response_deadline': 'Response Deadline',
    'response_progress': 'Response Progress',
    'request_content': 'Request Content',
    'request_attachments': 'Request Attachments',
    'download': 'Download',
    'supplier_response': 'Supplier Response',
    'send_reminder': 'Send Reminder',
    'export_details': 'Export Details',
    'cancel_request': 'Cancel Request',
    'select_request_view_details': 'Select a Request to View Details',
    'select_request_description': 'Select a request record from the list on the left to view detailed information and supplier responses',
    
    // Workspace Data Collections
    'data_collections': 'Data Collections',
    'product_carbon_data': 'Product Carbon Footprint Data',
    'production_process_data': 'Production Process Data',
    'last_updated': 'Last Updated',
    'view': 'View',
    'product_carbon_data_desc': 'Contains carbon footprint data for 50 different products',
    'production_process_data_desc': 'Contains energy consumption data for 30 different production processes',
    
    // Search Page
    'product_carbon_footprint_search': 'Product Carbon Footprint Search',
    'search_product_supplier_category': 'Search product name, supplier or category...',
    'filter': 'Filter',
    'filter_and_sort': 'Filter & Sort',
    'industry': 'Industry',
    'data_type': 'Data Type',
    'sort_by': 'Sort By',
    'clear_filters': 'Clear Filters',
    'applied_filters': 'Applied Filters',
    'search': 'Search',
    'sort': 'Sort',
    'clear_all': 'Clear All',
    'found': 'Found',
    'results': 'results',
    'no_results_found': 'No Results Found',
    'try_adjusting_search': 'Try adjusting your search criteria or filter options, or use our prediction feature to generate new carbon footprint data.',
    'start_new_prediction': 'Start New Prediction',
    'related_supplier_recommendations': 'Related Supplier Recommendations',
    'product_count': 'Product Count',
    
    // Workspace General
    'return_to_home': 'Return to Home',
    'return': 'Return',
    'menu': 'Menu',
    'workspace_modules': 'Workspace Modules',
    'function_modules': 'Function Modules',
    'pro_features': 'Pro Features',
    'pro_features_desc': 'Unlock more advanced features and data analysis with Pro version',
    'upgrade_to_pro': 'Upgrade to Pro',
    'close': 'Close',
    'data_request': 'Data Request',
    
    // Workspace Inference
    'carbon_footprint_prediction': 'Carbon Footprint Prediction',
    'new_prediction': 'New Prediction',
    'history_records': 'History Records',
    'in_progress': 'In Progress',
    'no_active_predictions': 'No active prediction tasks currently',
    'prediction_history_title': 'Prediction History',
    'history_prediction_list': 'History Prediction List',
    'view_details': 'View Details',
    
    // Workspace Data Request
    'new_request': 'New Request',
    'historical_requests': 'Historical Requests',
    'redirect_from_prediction': 'Redirected from Prediction Result',
    'creating_data_request': 'You are creating a data request for',
    'of_supplier': 'of',
    'creating_data_request_2': '.',
    'prefilled_info': 'We have pre-filled some information for you, please complete the remaining content.',

    // InferenceForm
    'product_name_placeholder': 'Product name (e.g., Organic Cotton T-shirt)',
    'product_category_placeholder': 'Product category (e.g., Textiles, Electronics)',
    'supplier_info': 'Supplier Information',
    'supplier_name_placeholder': 'Supplier name (e.g., Green Tech Co., Ltd.)',
    'product_description': 'Product Description (Optional)',
    'product_description_placeholder': 'Briefly describe product features, materials, manufacturing processes, etc., which will help improve prediction accuracy',
    'environmental_tips': 'Environmental Tips',
    'environmental_tips_desc': 'Providing detailed product information can help us predict carbon footprints more accurately. If you have product technical documentation, you can upload it after prediction to improve accuracy.',
    'cancel_prediction': 'Cancel Prediction',
    'save_draft': 'Save Draft',
    
    // PredictionResult
    'return_button': 'Return',
    'link_copied': 'Link Copied',
    'link_copied_desc': 'Prediction result link has been copied to clipboard',
    'prediction_needs_accuracy': 'Prediction data has uncertainty?',
    'prediction_accuracy_desc': 'The data shown on this page is only a prediction result and may differ from the actual situation. Request actual data from suppliers for more accurate carbon footprint analysis and emission reduction recommendations.',
    'need_more_accurate_data': 'Need more accurate data analysis?',
    'accurate_data_desc': 'By obtaining actual production data from suppliers, we can provide you with more precise carbon footprint analysis and emission reduction solutions. Send a data request to suppliers, which only takes a few minutes to complete.',
    'prediction_disclaimer': 'This result is derived from information disclosed by the company and related statistical data. It is only a prediction result and cannot fully reflect the actual production level of the supplier. For carbon accounting and certification scenarios, actual data should be used. When actual data is missing, industry average data will be used as default values.',
    'improvement_difficulty_easy': 'Easy',
    'improvement_difficulty_medium': 'Medium',
    'improvement_difficulty_hard': 'Hard',
    'potential_reduction': 'Potential Reduction',

    // Data Request Form
    'supplier_product_info_form': 'Supplier and Product Information',
    'supplier_name_form': 'Supplier Name',
    'supplier_name_placeholder_form': 'Enter supplier name',
    'product_name_form': 'Product Name',
    'product_name_placeholder_form': 'Enter product name',
    'contact_info_form': 'Contact Information',
    'contact_name_form': 'Contact Name',
    'contact_name_placeholder_form': 'Enter contact name',
    'contact_email_form': 'Contact Email',
    'contact_email_placeholder_form': 'Enter contact email',
    'contact_phone_form': 'Contact Phone (Optional)',
    'contact_phone_placeholder_form': 'Enter contact phone',
    'request_data_items': 'Requested Data Items',
    'request_data_items_description': 'Select the types of data you need from the supplier',
    'product_specs': 'Product Specifications',
    'material_composition': 'Material Composition',
    'manufacturing_process': 'Manufacturing Process',
    'energy_consumption': 'Energy Consumption Data',
    'transportation_logistics': 'Transportation & Logistics',
    'certifications': 'Certifications',
    'test_reports': 'Test Reports',
    'packaging_details': 'Packaging Details',
    'suppliers_info': 'Upstream Suppliers Information',
    'waste_data': 'Waste Management Data',
    'urgency_level': 'Urgency Level',
    'urgency_low': 'Low - Reply within a month',
    'urgency_medium': 'Medium - Reply within two weeks',
    'urgency_high': 'High - Reply within a week',
    'response_deadline_form': 'Response Deadline',
    'select_date': 'Select date',
    'additional_info_form': 'Additional Information (Optional)',
    'additional_info_placeholder': 'Enter any additional information or special requirements',
    'preview_request_ignore_validation': 'Preview Request (Ignore Validation)',
    'validate_and_preview': 'Validate and Preview',
    
    // Data Request Preview
    'data_request_preview': 'Data Request Preview',
    'confirm_content_accuracy': 'Please confirm the accuracy of the following content before sending',
    'supplier_info_label': 'Supplier Information',
    'supplier_name_label': 'Supplier Name',
    'product_info_label': 'Product Information',
    'product_name_label': 'Product Name',
    'contact_info_label': 'Contact Information',
    'contact_name_label': 'Contact Person',
    'contact_email_label': 'Email',
    'contact_phone_label': 'Phone',
    'request_details_label': 'Request Details',
    'requested_data': 'Requested Data',
    'urgency_level_label': 'Urgency Level',
    'response_deadline_label': 'Response Deadline',
    'additional_notes': 'Additional Notes',
    'email_info': 'Email Information',
    'email_subject': 'Email Subject',
    'email_content': 'Email Content',
    'carbon_footprint_chart': 'This email will include the following carbon footprint comparison chart:',
    'chart_note': 'Note: This chart will be sent as an image attachment or embedded in the content',
    'return_to_edit': 'Return to Edit',
    'confirm_send': 'Confirm and Send',
    
    // Email Content
    'email_subject_template': 'Carbon Footprint Data Collection for {product} - {supplier}',
    'email_greeting': 'Dear {supplier} Team,',
    'email_hello': 'Hello!',
    'email_intro_with_name': 'We are {name} from the procurement team at CarbonSleuth Environmental Technology Co., Ltd. We have been following your {product} and are very interested in its performance and environmental characteristics.',
    'email_intro_without_name': 'We are from the procurement team at CarbonSleuth Environmental Technology Co., Ltd. We have been following your {product} and are very interested in its performance and environmental characteristics.',
    'email_purpose': 'As a company that values sustainable development, we are conducting carbon footprint assessments for all products in our supply chain to create a more environmentally friendly product line. While reviewing your company\'s product information, we noticed that {product} is competitive in the industry, so we hope to obtain more detailed product carbon footprint data to make a more comprehensive assessment.',
    'current_prediction_title': '[Current Product Prediction Results]',
    'current_prediction_intro': 'According to our platform\'s preliminary carbon footprint prediction for {product}:',
    'current_prediction_value': '• Estimated carbon footprint: {value} {unit}',
    'current_prediction_confidence': '• Confidence level: {level}',
    'current_prediction_uncertainty': '• Uncertainty range: {range}',
    'current_prediction_contributors': '• Main contributing factors: {contributors}',
    'current_prediction_disclaimer': 'The above prediction results may differ from the actual situation. We hope to optimize this prediction by obtaining more accurate data.',
    'requested_items_intro': 'Specifically, we would like to obtain the following information:',
    'market_comparison_title': '[Market Comparison Data]',
    'industry_benchmark_title': '[Industry Benchmark Data]',
    'platform_prediction_title': '[About Platform Prediction Data]',
    'platform_prediction_desc': 'Please note that our platform\'s carbon footprint prediction data has the following characteristics:',
    'platform_prediction_point1': '• Prediction results are mainly based on publicly disclosed industry data and AI inference technology',
    'platform_prediction_point2': '• Prediction data has a certain degree of uncertainty (usually within ±15%)',
    'platform_prediction_point3': '• Prediction results may not fully reflect actual production conditions or specific process differences',
    'platform_prediction_point4': '• Obtaining your actual data will help us improve prediction accuracy and provide you with more targeted carbon reduction suggestions',
    'reports_intro': 'Here are some relevant industry reports we have compiled that you might find interesting:',
    'data_submission_title': '[Data Submission Link]',
    'data_submission_desc': 'To facilitate your data submission, we have created a dedicated data submission page that you can access via the following link:',
    'data_submission_security': 'This link is a secure link specially generated for your company. You can submit data directly without registration. The link is valid for 30 days.',
    'closing_with_deadline': 'If your company can provide this data, it will greatly help us evaluate the environmental performance of {product} in our supply chain and lay the foundation for possible future cooperation. Due to project schedule arrangements, we hope to receive the relevant information by {deadline}. This request is {urgency}.',
    'closing_without_deadline': 'If your company can provide this data, it will greatly help us evaluate the environmental performance of {product} in our supply chain and lay the foundation for possible future cooperation. We hope to receive your reply as soon as possible. This request is {urgency}.',
    'additional_info_section': 'Additional information:\n{info}',
    'email_thanks': 'Thank you for your attention and support! We look forward to further cooperation with your company.',
    'email_closing': 'Best regards,',
    'email_signature': '{name}\n{email}\n{phone}\nCarbonSleuth Environmental Technology Co., Ltd.',
    'urgency_text_low': 'low priority',
    'urgency_text_medium': 'normal priority',
    'urgency_text_high': 'high priority',
    'unspecified_supplier': 'Unspecified Supplier',
    'unspecified_product': 'Unspecified Product',
    'unspecified_contact': 'Unspecified Contact',
    'unspecified_email': 'Unspecified Email',
    'no_items_selected': 'No items selected',
    'asap': 'as soon as possible',
    
    // Prediction Confidence Levels
    'confidence_level_low': 'Low',
    'confidence_level_medium': 'Medium',
    'confidence_level_high': 'High',
    
    // Prediction Contributors
    'contributor_materials': 'Materials Production',
    'contributor_manufacturing': 'Manufacturing Process',
    'contributor_transportation': 'Transportation',
    
    // Inference Stages
    'stage_collecting_info': 'Collecting product basic information...',
    'stage_analyzing_composition': 'Analyzing product composition...',
    'stage_getting_tech_info': 'Getting production technology information...',
    'stage_identifying_competitors': 'Identifying relevant competitor suppliers...',
    'stage_building_lca': 'Building LCA model...',
    'stage_calculating_footprint': 'Calculating carbon footprint...',
    'stage_generating_report': 'Generating prediction report...',
    'stage_prediction_complete': 'Prediction complete!',
    'estimated_completion_time': 'Estimated completion time: 40-60 seconds',
    
    // Form Validation
    'required_fields_error': 'Please provide both product name and supplier name',
    'product_name_required': 'Please enter product name',
    'supplier_name_required': 'Please enter supplier name',
    'validation_error': 'Form Validation Error',
    
    // LCA Model Card
    'lca_model_flowchart': 'LCA Model Flowchart',

    // Recommendation Page
    'low_carbon_recommendation': 'Low Carbon Recommendations',
    'recommendation_description': 'Discover excellent low-carbon suppliers, products, and best practices to accelerate your sustainability journey',
    'search_recommendations': 'Search recommendations...',
    'low_carbon_suppliers': 'Low Carbon Suppliers',
    'low_carbon_products': 'Low Carbon Products',
    'carbon_reduction_best_practices': 'Carbon Reduction Best Practices',
    'all_industries': 'All Industries',
    'renewable_energy': 'Renewable Energy',
    'material_science': 'Material Science',
    'energy_storage': 'Energy Storage',
    'electronics_manufacturing': 'Electronics Manufacturing',
    'building_materials': 'Building Materials',
    'all_categories': 'All Categories',
    'solar_energy': 'Solar Energy',
    'wind_energy': 'Wind Energy',
    'battery_technology': 'Battery Technology',
    'composite_materials': 'Composite Materials',
    'smart_hardware': 'Smart Hardware',
    'green_building_materials': 'Green Building Materials',
    'all_regions': 'All Regions',
    'east_china': 'East China',
    'south_china': 'South China',
    'north_china': 'North China',
    'central_china': 'Central China',
    'west_china': 'Western China',
    'sort_by': 'Sort By',
    'carbon_performance_score': 'Carbon Performance Score',
    'overall_rating': 'Overall Rating',
    'latest_added': 'Latest Added',
    'all_data': 'All Data',
    'measured_data': 'Measured Data',
    'predicted_data': 'Predicted Data',
    'carbon_reduction_level': 'Carbon Reduction Level',
    'significant_reduction': 'Significant Reduction (>40%)',
    'medium_reduction': 'Medium Reduction (20-40%)',
    'slight_reduction': 'Slight Reduction (<20%)',
    'reduction_magnitude': 'Reduction Magnitude',
    'carbon_footprint_value': 'Carbon Footprint Value',
    'industry_applicability': 'Industry Applicability',
    'manufacturing': 'Manufacturing',
    'energy_industry': 'Energy Industry',
    'chemical_industry': 'Chemical Industry',
    'electronics_industry': 'Electronics Industry',
    'automotive_industry': 'Automotive Industry',
    'implementation_difficulty': 'Implementation Difficulty',
    'easy_to_implement': 'Easy to Implement',
    'medium_difficulty': 'Medium Difficulty',
    'high_difficulty': 'High Difficulty',
    'return_on_investment_period': 'Return on Investment Period',
    'all_periods': 'All Periods',
    'short_term': 'Short Term (<1 year)',
    'medium_term': 'Medium Term (1-3 years)',
    'long_term': 'Long Term (>3 years)',
    'carbon_reduction_effect': 'Carbon Reduction Effect',
    'return_on_investment': 'Return on Investment',
    'load_more': 'Load More',
    'carbon_performance': 'Carbon Performance',
    'low_carbon_highlights': 'Low Carbon Highlights',
    'product_coverage': 'Product Coverage',
    'view_details': 'View Details',
    'industry_average': 'Industry Average',
    'carbon_reduction_highlights': 'Carbon Reduction Highlights',
    'implementation_results': 'Implementation Results',
    
    // Stats
    'carbon_footprint_data_count': 'Carbon Footprint Data Count',
    'industry_coverage_count': 'Industry Coverage Count',
    'average_carbon_reduction_potential': 'Average Carbon Reduction Potential',
    'user_satisfaction_rate': 'User Satisfaction Rate',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  // Get initial language from localStorage or use browser language
  const getInitialLanguage = (): Language => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'zh'].includes(savedLanguage)) {
      return savedLanguage;
    }
    
    // Try to detect from browser
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith('zh') ? 'zh' : 'en';
  };
  
  const [language, setLanguage] = useState<Language>(getInitialLanguage);
  
  // Update localStorage when language changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);
  
  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };
  
  const value = {
    language,
    setLanguage,
    t
  };
  
  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
